import type { OnboardingStep } from "@/types/database";

export type RejectionKind = "brand" | "campaign";

export const SUPPORT_EMAIL = "support@simplassist.com";

// Ordered: identity checks run before content checks because carrier texts
// citing brand identity often also contain generic words like "description".
// Carrier codes: 808/810 = identity/EIN verification; 861 = missing opt-out
// language in sample messages; 708 = message flow / call-to-action issues.
const IDENTITY_PATTERN =
  /(\bein\b|tax id|legal name|identity|vetting|brand verification|registration number|address mismatch|\b808\b|\b810\b)/i;
// "opt(ing/ed/s) out" needs explicit alternatives: `opt.?out` cannot span
// the suffix, and the opt-in pattern's trailing \b keeps it out of "opting".
const OPT_OUT_PATTERN = /(opt(?:ing|ed|s)?[ -]?out|unsubscribe|\bstop\b|\b861\b)/i;
// Unambiguous message-flow / call-to-action evidence, including the explicit
// carrier code: that text is SimplAssist-generated, so it outranks keyword
// overlap with customer-owned fields (samples, use-case description).
const MESSAGE_FLOW_PATTERN = /(call.?to.?action|\bcta\b|message flow|\b708\b)/i;
// Ambiguous consent/opt-in wording: checked only AFTER the self-serve
// categories (sample, use case), because "recipients consent" in a use-case
// rejection points at the customer's own description, not our generated text.
const OPT_IN_PATTERN = /(\bopt[ -]?ins?\b|consent)/i;
const SAMPLE_PATTERN = /(sample|example message)/i;
const USE_CASE_PATTERN = /(use.?case|description|vague|insufficient|unclear)/i;
const CONTENT_PATTERN =
  /(prohibited|disallowed|restricted|cannabis|firearm|gambl|lending|\bloan\b|alcohol|tobacco|content)/i;
// Deliberately no bare "privacy"/"terms": phrases like "violates our terms
// of service" are policy wording, not a website problem.
const URL_PATTERN =
  /(\burl\b|website|\blink\b|landing page|privacy policy|privacy page|privacy notice|privacy statement|terms page|terms and conditions|terms & conditions)/i;

type RejectionCategory =
  | "identity"
  | "opt_out"
  | "opt_in"
  | "sample"
  | "use_case"
  | "content"
  | "url"
  | null;

function classifyRejection(
  kind: RejectionKind,
  reason: string | null | undefined
): RejectionCategory {
  const text = reason ?? "";
  if (IDENTITY_PATTERN.test(text)) return "identity";
  // Content patterns only apply to campaign rejections: generic quality
  // wording ("insufficient", "unclear", "description") in a BRAND rejection
  // refers to brand data, not campaign content.
  if (kind === "campaign") {
    // An explicit 861 (missing opt-out in samples) beats message-flow
    // keywords, mirroring how the explicit 708 beats opt-out keywords below.
    if (/\b861\b/.test(text)) return "opt_out";
    // Explicit message-flow evidence (708, "message flow", CTA) outranks
    // everything else on the campaign side — real 708 boilerplate routinely
    // embeds "STOP opt-out" wording, and the message flow is our generated
    // text, so opt-out keywords must not steal it into the self-serve path.
    // The ambiguous consent/opt-in words rank below the self-serve
    // categories AND below url, so wording aimed at customer-owned fields
    // (samples, use-case description, website/privacy pages) keeps its
    // routed fix path.
    if (MESSAGE_FLOW_PATTERN.test(text)) return "opt_in";
    if (OPT_OUT_PATTERN.test(text)) return "opt_out";
    if (SAMPLE_PATTERN.test(text)) return "sample";
    if (USE_CASE_PATTERN.test(text)) return "use_case";
    if (URL_PATTERN.test(text)) return "url";
    if (OPT_IN_PATTERN.test(text)) return "opt_in";
    if (CONTENT_PATTERN.test(text)) return "content";
  }
  if (URL_PATTERN.test(text)) return "url";
  return null;
}

/**
 * Best-effort inference of which onboarding step a carrier rejection points
 * at, so "Fix & resubmit" can land the customer on the right form.
 *
 * Returns null for the opt-in / message-flow class (code 708): that wording
 * is generated by SimplAssist and customer edits never reach the carrier, so
 * the honest path is support, not a form that ignores their input.
 *
 * Unrecognized or ambiguous reasons fall back to the earliest relevant step
 * for the rejection kind (brand → Business Verification, campaign → SMS Use
 * Case). Inference never blocks anything, and callers keep showing the full
 * raw reason regardless.
 */
export function inferRejectionStep(
  kind: RejectionKind,
  reason: string | null | undefined
): OnboardingStep | null {
  switch (classifyRejection(kind, reason)) {
    case "identity":
      return "legal_verification";
    case "opt_out":
    case "sample":
    case "use_case":
    case "content":
      return "sms_use_case";
    case "opt_in":
      return null; // support path — see docstring
    case "url":
      // Brand url = the business website field. Campaign url = the privacy/
      // terms links on the registration, which no onboarding form owns
      // (overrides live in dashboard Settings → Compliance; hosted pages are
      // SimplAssist-generated) — support path.
      return kind === "brand" ? "business_info" : null;
    default:
      return kind === "brand" ? "legal_verification" : "sms_use_case";
  }
}

/**
 * True when the rejection class cannot be fully resolved self-serve, so the
 * panel should surface a Contact-support action alongside (or instead of)
 * the routed form:
 * - opt_in / message flow: that text is generated by SimplAssist, so
 *   customer edits never reach the carrier.
 * - campaign-kind identity: the flagged fields live on the brand, and a
 *   campaign retry re-files only the campaign — an approved brand is never
 *   re-filed.
 * Brand-kind rejections are fully self-serve: the retry pipeline archives
 * the rejected brand and re-files a replacement with the corrected details
 * (archiveAndClearRejectedBrand).
 */
export function rejectionNeedsSupport(
  kind: RejectionKind,
  reason: string | null | undefined
): boolean {
  if (kind === "brand") return false;
  const category = classifyRejection(kind, reason);
  // campaign url: the flagged links are dashboard-Settings overrides or
  // SimplAssist-generated pages — either way not fixable from the wizard.
  return category === "opt_in" || category === "identity" || category === "url";
}

/**
 * Plain-English explanation of a carrier rejection for non-technical
 * customers (Approach A: light string mapper). Returns null when the reason
 * doesn't match a known category — callers fall back to the raw text plus a
 * contact-support line. The raw carrier wording is always shown alongside,
 * smaller, for support/debugging.
 */
export function mapReasonToFriendly(
  kind: RejectionKind,
  reason: string | null | undefined
): string | null {
  switch (classifyRejection(kind, reason)) {
    case "identity":
      // Brand-kind: retry archives the rejected brand and re-files a
      // replacement, so the fix is self-serve. Campaign-kind: the flagged
      // fields live on the (approved) brand, which a campaign retry never
      // re-files — support path.
      return kind === "brand"
        ? "Carriers couldn't verify your business identity. Double-check your legal business name, EIN, and business address — they need to exactly match what's on file with the IRS and your state. Even a small difference like 'LLC' vs 'L.L.C.' can cause this. Update your details, then hit Retry registration — we'll re-file your verification with the carrier automatically. It's usually a quick fix."
        : `Carriers couldn't verify your business identity. Double-check your legal business name, EIN, and business address — they need to exactly match what's on file with the IRS and your state. Even a small difference like 'LLC' vs 'L.L.C.' can cause this. Update your details, then contact support at ${SUPPORT_EMAIL} and we'll re-file your verification with you — it's usually a quick fix.`;
    case "opt_out":
      return "One or more of your sample messages is missing opt-out wording. Add a line like 'Reply STOP to unsubscribe' to each sample message and resubmit — a quick fix.";
    case "opt_in":
      return `This rejection is about the opt-in explanation SimplAssist generates for you — it's ours to fix, not yours. Contact support at ${SUPPORT_EMAIL} and we'll adjust it and resubmit with you.`;
    case "sample":
      return "Your example texts didn't pass review. Make sure your sample messages sound like real texts you'd send a customer, mention your business name, and at least one says 'Reply STOP to opt out.' A quick polish usually does it.";
    case "use_case":
      return "Carriers need a clearer picture of what you'll text customers about. Rewrite your SMS description in plain terms — appointment reminders, follow-ups after missed calls, answers to customer questions. A couple of clear sentences is all it takes.";
    case "content":
      return "Carriers flagged your message content as a restricted category. Review your SMS description and sample messages and remove anything related to restricted topics (like cannabis, firearms, or lending). If this looks like a mistake, contact support and we'll appeal it with you.";
    case "url":
      // Brand-kind url is the business website field: retry re-files the
      // brand with the corrected website, so the fix is self-serve (a
      // website change also re-triggers the A2P risk screen — the URL is a
      // hashed screening input). Campaign-kind url is about the
      // registration's privacy/terms links: the submitted campaign contains
      // no website URL. Don't point at Settings → Compliance — the
      // dashboard is unreachable while a rejection is showing
      // (dashboardReady is false), so the only self-serve lever is the
      // customer's own site being down; everything else (wrong override
      // value, our hosted pages) is support's.
      return kind === "brand"
        ? "Carriers couldn't verify your website or your privacy and terms pages. Make sure your website address is correct and loads for visitors, then hit Retry registration — we'll re-file your verification with the carrier automatically. (Your SimplAssist privacy and terms pages are generated automatically — if you use your own links, check those.)"
        : `Carriers couldn't load the privacy or terms links on your SMS registration. If you use your own privacy and terms pages, make sure those links load for visitors, then retry. If they look fine — or you use the SimplAssist-generated pages — contact support at ${SUPPORT_EMAIL} and we'll fix it with you.`;
    default:
      return null;
  }
}
